# Generated by Django 4.2.6 on 2023-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource", "0002_resource_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
