# Generated by Django 4.2.6 on 2023-11-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="response_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
