# Generated by Django 4.2.6 on 2023-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_contactus_response_contactus_response_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="closed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
