# Generated by Django 4.2.6 on 2023-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentor",
            name="username",
            field=models.CharField(default="AnonymousUser", max_length=300),
        ),
    ]
