# Generated by Django 4.2.6 on 2023-11-02 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_mentor_approved_mentor_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="last_application_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 2, 17, 17, 32, 454584, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
