# Generated by Django 4.2.6 on 2023-11-03 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branch", "0001_initial"),
        ("account", "0003_mentor_last_application_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "club_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("club_name", models.CharField(max_length=200, unique=True)),
                ("club_desc", models.CharField(max_length=200)),
                (
                    "club_logo",
                    models.ImageField(blank=True, null=True, upload_to="club_logo/"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="branch.branch"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mentor",
            name="last_application_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 3, 10, 56, 23, 660396, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_head", models.BooleanField(default=False)),
                ("social_media_manager", models.BooleanField(default=False)),
                (
                    "joined_on",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2023,
                            11,
                            3,
                            10,
                            56,
                            23,
                            662399,
                            tzinfo=datetime.timezone.utc,
                        ),
                        null=True,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.club"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
