# Generated by Django 4.2.6 on 2023-11-03 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_club_alter_mentor_last_application_date_clubmember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmember",
            name="club",
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="joined_on",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 3, 11, 4, 25, 102103, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="last_application_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 3, 11, 4, 25, 100118, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="club",
            field=models.ManyToManyField(to="account.club"),
        ),
    ]
