# Generated by Django 4.2.6 on 2023-11-03 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("account", "0005_remove_clubmember_club_alter_clubmember_joined_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="club",
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="joined_on",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 3, 11, 8, 56, 534028, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="last_application_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2023, 11, 3, 11, 8, 56, 531031, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="branch",
            field=models.ManyToManyField(to="branch.branch"),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.club",
            ),
        ),
    ]
