# Generated by Django 4.2.6 on 2023-11-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="branch",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="branches", to="branch.branch"
            ),
        ),
    ]
