# Generated by Django 4.2.6 on 2023-11-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0001_initial"),
        ("announcement", "0002_announcement_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="branch",
            field=models.ManyToManyField(related_name="branches", to="branch.branch"),
        ),
    ]
