# Generated by Django 4.2.6 on 2023-11-04 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_remove_post_branch_post_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="published_date",
        ),
    ]
